"use client";
import { FormEvent, useMemo, useState } from "react";

const products = [
  { id: "pastelitos", name: "Pastelitos", detail: "Pequeños, personales y llenos de detalle", price: "Desde $12.000", base: 12000, image: "https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=900&q=85" },
  { id: "mini-cake", name: "Mini cakes", detail: "Para celebrar bonito entre 3 y 5 personas", price: "Desde $45.000", base: 45000, image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587e?auto=format&fit=crop&w=900&q=85" },
  { id: "ponque", name: "Ponqués", detail: "Cumpleaños, matrimonios y grandes momentos", price: "Desde $95.000", base: 95000, image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=900&q=85" },
];
const money = new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 });

export default function Home() {
  const [product, setProduct] = useState(products[1]);
  const [delivery, setDelivery] = useState("domicilio");
  const [sent, setSent] = useState(false);
  const total = product.base + (delivery === "domicilio" ? 8000 : 0);
  const deposit = useMemo(() => total / 2, [total]);
  function submitOrder(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const summary = `Hola Dulcemente, quiero cotizar un pedido.%0A%0AProducto: ${product.name}%0ACliente: ${data.get("name")}%0ATeléfono: ${data.get("phone")}%0ACorreo: ${data.get("email")}%0AEntrega: ${data.get("date")} a las ${data.get("time")}%0AModalidad: ${delivery}%0ADirección: ${data.get("address")}%0AIdea: ${data.get("details")}%0A%0AAbono estimado: ${money.format(deposit)}`;
    setSent(true); window.open(`https://wa.me/?text=${summary}`, "_blank", "noopener,noreferrer");
  }
  return <main>
    <nav className="nav wrap" aria-label="Navegación principal"><a className="brand" href="#inicio">dulce<span>mente</span><i>•</i></a><div className="navlinks"><a href="#coleccion">Colección</a><a href="#nosotros">Nuestra esencia</a><a className="navCta" href="#pedido">Hacer un pedido</a></div></nav>
    <section className="hero wrap" id="inicio"><div className="heroCopy"><p className="eyebrow">Pastelería artesanal · Hecho con calma</p><h1>Momentos que saben <em>dulce.</em></h1><p className="lead">Creamos pasteles únicos, decorados a mano para que cada celebración tenga un pedacito de ti.</p><div className="heroActions"><a className="button" href="#pedido">Quiero el mío <span>→</span></a><a className="textLink" href="#coleccion">Ver delicias</a></div><div className="miniProof"><span>✿</span><p><strong>100% hecho a mano</strong><br/>Personalizamos cada detalle</p></div></div><div className="heroVisual"><div className="arch"><img src="https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=1200&q=90" alt="Pastel artesanal decorado con flores"/></div><span className="stamp">HECHO CON<br/><b>♥</b><br/>PARA TI</span><div className="note">Cada pastel cuenta<br/><em>una historia</em></div></div></section>
    <section className="collection wrap" id="coleccion"><div className="sectionHead"><div><p className="eyebrow">Algo especial para cada ocasión</p><h2>Elige tu antojo</h2></div><p>Sabores caseros, ingredientes frescos y ese toque artesanal que se nota desde la primera mirada.</p></div><div className="productGrid">{products.map((item) => <article className="product" key={item.id}><button className="productImage" onClick={() => { setProduct(item); document.querySelector("#pedido")?.scrollIntoView(); }} aria-label={`Pedir ${item.name}`}><img src={item.image} alt={item.name}/><span>Elegir ↗</span></button><div className="productMeta"><div><h3>{item.name}</h3><p>{item.detail}</p></div><strong>{item.price}</strong></div></article>)}</div></section>
    <section className="essence" id="nosotros"><div className="wrap essenceGrid"><div className="essenceImage"><img src="https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=1000&q=85" alt="Cupcakes decorados artesanalmente"/><span>Desde nuestra cocina<br/>con mucho amor ♡</span></div><div className="essenceCopy"><p className="eyebrow">Nuestra esencia</p><h2>No hacemos pasteles en serie. Hacemos recuerdos.</h2><p>Todo empieza con una conversación: tus colores, tus sabores y la historia que quieres celebrar. Después vienen las manos, la paciencia y los pequeños detalles.</p><ul><li><b>01</b><span><strong>Diseño a tu medida</strong>Inspirado en tu ocasión y en las personas que amas.</span></li><li><b>02</b><span><strong>Ingredientes que reconoces</strong>Preparaciones frescas, sin atajos y con sabor casero.</span></li><li><b>03</b><span><strong>Entrega con cuidado</strong>Coordinamos cada pedido para que llegue impecable.</span></li></ul></div></div></section>
    <section className="orderSection" id="pedido"><div className="wrap orderIntro"><p className="eyebrow">Empecemos tu pedido</p><h2>Hagamos algo <em>inolvidable.</em></h2><p>Completa los datos para recibir la confirmación, la cotización final y el enlace seguro de pago.</p></div><form className="orderForm wrap" onSubmit={submitOrder}><div className="formBody"><fieldset><legend>1. ¿Qué quieres celebrar?</legend><div className="choiceGrid">{products.map((item) => <label className={product.id === item.id ? "choice active" : "choice"} key={item.id}><input type="radio" name="product" value={item.id} checked={product.id === item.id} onChange={() => setProduct(item)}/><span>{item.name}</span><small>{item.price}</small></label>)}</div></fieldset><fieldset><legend>2. Tus datos</legend><div className="fieldGrid"><label>Nombre completo<input name="name" autoComplete="name" required placeholder="¿Cómo te llamas?"/></label><label>Teléfono<input name="phone" type="tel" autoComplete="tel" required placeholder="300 000 0000"/></label><label>Correo electrónico<input name="email" type="email" autoComplete="email" required placeholder="tu@correo.com"/></label><label>Fecha de entrega<input name="date" type="date" required/></label><label>Hora de entrega<input name="time" type="time" required/></label><label>Entrega<select name="delivery" value={delivery} onChange={(e) => setDelivery(e.target.value)}><option value="domicilio">Domicilio (+ $8.000)</option><option value="recoger">Recoger en taller</option></select></label><label className="full">Dirección o ubicación<input name="address" autoComplete="street-address" required={delivery === "domicilio"} placeholder={delivery === "domicilio" ? "Dirección, barrio y referencias" : "No es necesaria si recoges"}/></label><label className="full">Cuéntanos tu idea<textarea name="details" rows={4} required placeholder="Ocasión, sabores, colores, mensaje, número de porciones y referencias…"/></label></div></fieldset></div><aside className="summary"><p className="eyebrow">Resumen estimado</p><h3>{product.name}</h3><div className="sumRow"><span>Base del pedido</span><b>{money.format(product.base)}</b></div><div className="sumRow"><span>{delivery === "domicilio" ? "Domicilio" : "Recogida"}</span><b>{delivery === "domicilio" ? money.format(8000) : "$0"}</b></div><div className="sumTotal"><span>Total estimado</span><b>{money.format(total)}</b></div><div className="deposit"><span>Abono para reservar · 50%</span><strong>{money.format(deposit)}</strong></div><p className="fineprint">El valor final puede variar según porciones y decoración. Te confirmaremos la cotización antes de enviarte el enlace de pago.</p><button className="button submit" type="submit">Enviar pedido <span>→</span></button>{sent && <p className="success">¡Listo! Abriendo tu solicitud en WhatsApp.</p>}<small className="secure">⌁ Pago seguro después de confirmar disponibilidad</small></aside></form></section>
    <footer><div className="wrap footerGrid"><div><a className="brand footerBrand" href="#inicio">dulce<span>mente</span><i>•</i></a><p>Pasteles hechos a mano<br/>para historias que merecen celebrarse.</p></div><div><strong>Explora</strong><a href="#coleccion">Colección</a><a href="#nosotros">Nuestra esencia</a><a href="#pedido">Pedidos</a></div><div><strong>Hablemos</strong><a href="mailto:hola@dulcemente.co">hola@dulcemente.co</a><a href="#pedido">WhatsApp</a><span>Lun–Sáb · 9:00–18:00</span></div></div><div className="wrap copyright"><span>© 2026 Dulcemente</span><span>Hecho con paciencia y un poquito de azúcar.</span></div></footer>
  </main>;
}
